name: Code checkers

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install poetry
          python -m poetry install

      - name: Run linter
        run: make linter

      - name: Run format control
        run: make format_diff

      - name: Run test
        run: make test
